# Generated by Django 5.2.4 on 2025-08-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_workspace_alter_costcenter_workspace_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostCenter',
        ),
    ]
