# Generated by Django 5.2.4 on 2025-08-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_alter_beneficiary_unique_together_and_more'),
        ('transactions', '0002_remove_transaction_cost_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='beneficiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='beneficiaries.beneficiary', verbose_name='Beneficiário'),
        ),
    ]
