# Generated by Django 5.2.4 on 2025-08-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_beneficiario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
    ]
