# Generated by Django 5.2.4 on 2025-07-29 00:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], default='mensal', max_length=15)),
                ('mes', models.IntegerField(blank=True, help_text='Mês (1-12) para orçamentos mensais', null=True)),
                ('ano', models.IntegerField()),
                ('data_inicio', models.DateField(blank=True, help_text='Para orçamentos personalizados', null=True)),
                ('data_fim', models.DateField(blank=True, help_text='Para orçamentos personalizados', null=True)),
                ('valor_planejado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-ano', '-mes', 'nome'],
                'unique_together': {('user', 'nome', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_planejado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='budgets.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Categoria do Orçamento',
                'verbose_name_plural': 'Categorias do Orçamento',
                'unique_together': {('budget', 'category')},
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('percentual', 'Percentual'), ('valor_fixo', 'Valor Fixo')], max_length=15)),
                ('valor_limite', models.DecimalField(decimal_places=2, help_text='Valor em reais ou percentual (0-100)', max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('notificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='budgets.budgetcategory')),
            ],
            options={
                'verbose_name': 'Alerta de Orçamento',
                'verbose_name_plural': 'Alertas de Orçamento',
            },
        ),
    ]
