# Generated by Django 5.2.4 on 2025-07-31 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('formato_arquivo', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('ofx', 'OFX')], max_length=10)),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_processados', models.IntegerField(default=0)),
                ('registros_erro', models.IntegerField(default=0)),
                ('registros_duplicados', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='processando', max_length=15)),
                ('log_erros', models.JSONField(default=list, help_text='Log dos erros encontrados')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_history', to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Importação',
                'verbose_name_plural': 'Histórico de Importações',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('transacoes', 'Transações'), ('categorias', 'Por Categorias'), ('contas', 'Por Contas'), ('orcamentos', 'Orçamentos'), ('fluxo_caixa', 'Fluxo de Caixa'), ('comparativo', 'Comparativo')], max_length=20)),
                ('periodo', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('personalizado', 'Personalizado')], max_length=15)),
                ('filtros', models.JSONField(default=dict, help_text='Filtros aplicados ao relatório')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dados', models.JSONField(default=dict, help_text='Dados do relatório em cache')),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('is_favorito', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'nome')},
            },
        ),
    ]
