# Generated by Django 5.2.4 on 2025-08-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_profile_fields'),
        ('beneficiaries', '0002_remove_beneficiary_unique_beneficiary_per_workspace_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Beneficiário'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='tipo',
            field=models.CharField(choices=[('pessoa_fisica', 'Pessoa Física'), ('pessoa_juridica', 'Pessoa Jurídica'), ('conta_bancaria', 'Conta Bancária'), ('cartao_credito', 'Cartão de Crédito'), ('pix', 'PIX'), ('estabelecimento', 'Estabelecimento'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together={('nome', 'workspace')},
        ),
    ]
